url: https://giadatanghetti.it/
baseurl: ""

# Site settings
title: Musicoterapia con Giada
email: tanghettigiada@gmail.com
description: "Musicoterapia con Giada Tanghetti - Musicoterapeuta, Educatrice & Cantante. Opera in provincia di Brescia, sul lago di Garda (Salò)."
keywords: giada, tanghetti, musicoterapia, propedeutica, educazione, infanzia, asilo, musicoterapeuta, canto, cantante, salò, brescia, garda, lago

# Postal address (add as many lines as necessary)
address:
  - line: Centro FA.BA
  - line: Via Alcide de Gasperi 9B
  - line: Villanuova sul Clisi, 25087, Brescia, Italia

# Build settings
markdown: kramdown
permalink: pretty
